### PR TITLE
Add tests to sources api

### PR DESCRIPTION
**Pull request by rezigned**
Add tests to sources API.

### CODE REVIEW

**Comment by varshard** [comment]
@rezigned Thank you for contribution.

I think Vadim's decision to  bump version from 0.7 to 1.1.0 is too high, though.

The latest version is 0.7.1. So, I think it should be bumped it o just 0.7.2.

**Comment by robinclart** [comment]
@varshard Since it's new stuff you can move to 0.8.0.

**Comment by rezigned** [comment]
Update version to "0.8.0"

**Review by varshard — APPROVED** [review]

**Comment by varshard** [comment]
@rezigned Please resolve conflict.

**Comment by rezigned** [comment]
@varshard Resolved :)

**Pull request merged**
