### PR TITLE
Capabilities

### PR DESCRIPTION
**Pull request by jonrandy**
Adds simple functionality to use the `Capability` API

### CODE REVIEW

**Comment by robinclart** [comment]
Hey @jonrandy. I'm taking care of updating this library this week. Will merge this once I'm done with some updates I'm currently doing in another part.

**Comment by jonrandy** [comment]
You read my mind. I was considering updating this to the new capability API just this morning as I will need it fairly soon for Shopify

**Comment by jonrandy** [comment]
Should I go ahead and change this so it is for the new Capability API, or... ?

**Comment by jonrandy** [comment]
@robinclart Is the capabilities stuff complete?

**Pull request merged**
